import Head from 'next/head'
import Image from 'next/image'

export default function Home() {
  return (
    <div className="max-w-screen min-h-screen flex justify-center items-center bg-dark-cyan">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app " />
        <link rel="icon" type="image/png" href="/images/favicon.png" />
      </Head>

        <div className="max-w-xl w-80 h-80  mx-6 my-10 bg-white rounded-xl flex flex-col items-center drop-shadow-2xl">
            <div className='noSelect w-full relative h-32'>
              <Image src="/images/bg-pattern-card.svg"
              layout="fill"
              objectFit='cover'
              alt="banner"
              className='rounded-t-xl'/>

          </div>

          <div className=' relative w-full flex flex-col items-center'>

            <div className='noSelect absolute -top-9 rounded-full w-20 h-20 border-4 border-white'>
              <Image
              src="/images/image-victor.jpg"
              layout='fill'
              alt="avatar"
              className='rounded-full'/>
            </div>

            <h2 className='mt-14'><span className='dark-blue font-bold'>Victor Crest</span> 26</h2>
            <p className='mb-4 text-xs font-bold'>London</p>

            <div className='w-full h-20 px-2 flex flex-row justify-center border-t border-gray justify-around text-xs'>


              <div className='flex flex-col justify-center items-center'>
                <h1 className='text-xl font-bold dark-blue'>80K</h1>
                <p>Followers</p>

              </div>

              <div className='flex flex-col justify-center items-center'>
                <h1 className='text-xl font-bold dark-blue'>803K</h1>
                <p>Likes</p>


              </div>

              <div className='flex flex-col justify-center items-center'>
                <h1 className='text-xl font-bold dark-blue'>1.4K</h1>
                <p>Photos</p>


              </div>


            </div>



          </div>
        </div>
      
    </div>
  )
}
